import re
import jellyfish
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from pyjarowinkler import distance
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

# Download stop words and lemmatization data
nltk.download('stopwords')
nltk.download('wordnet')

badwords = [
    "2 girls 1 cup",
    "2g1c",
    "4r5e",
    "5h1t",
    "5hit",
    "a$$",
    "a$$hole",
    "a_s_s",
    "a2m",
    "a54",
    "a55",
    "a55hole",
    "aeolus",
    "ahole",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "anal impaler",
    "anal leakage",
    "analannie",
    "analprobe",
    "analsex",
    "anilingus",
    "anus",
    "apeshit",
    "ar5e",
    "areola",
    "areole",
    "arian",
    "arrse",
    "arse",
    "arsehole",
    "aryan",
    "ass",
    "ass fuck",
    "ass hole",
    "assault",
    "assbag",
    "assbagger",
    "assbandit",
    "assbang",
    "assbanged",
    "assbanger",
    "assbangs",
    "assbite",
    "assblaster",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfaces",
    "assfuck",
    "assfucker",
    "ass-fucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "asshat",
    "ass-hat",
    "asshead",
    "assho1e",
    "asshole",
    "assholes",
    "asshopper",
    "asshore",
    "ass-jabber",
    "assjacker",
    "assjockey",
    "asskiss",
    "asskisser",
    "assklown",
    "asslick",
    "asslicker",
    "asslover",
    "assman",
    "assmaster",
    "assmonkey",
    "assmucus",
    "assmunch",
    "assmuncher",
    "assnigger",
    "asspacker",
    "asspirate",
    "ass-pirate",
    "asspuppies",
    "assranger",
    "assshit",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswhore",
    "asswipe",
    "asswipes",
    "auto erotic",
    "autoerotic",
    "axwound",
    "azazel",
    "azz",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "babe",
    "babeland",
    "babes",
    "baby batter",
    "baby juice",
    "badfuck",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balllicker",
    "balls",
    "ballsack",
    "bampot",
    "bang",
    "bang (one's) box",
    "bangbros",
    "banger",
    "banging",
    "bareback",
    "barely legal",
    "barenaked",
    "barf",
    "barface",
    "barfface",
    "bastard",
    "bastardo",
    "bastards",
    "bastinado",
    "batty boy",
    "bawdy",
    "bazongas",
    "bazooms",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beardedclam",
    "beastial",
    "beastiality",
    "beatch",
    "beater",
    "beatyourmeat",
    "beaver",
    "beaver cleaver",
    "beaver lips",
    "beef curtain",
    "beef curtains",
    "beer",
    "beeyotch",
    "bellend",
    "bender",
    "beotch",
    "bestial",
    "bestiality",
    "bi+ch",
    "biatch",
    "bicurious",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bigbastard",
    "bigbutt",
    "bigger",
    "bigtits",
    "bimbo",
    "bimbos",
    "bint",
    "birdlock",
    "bisexual",
    "bi-sexual",
    "bitch",
    "bitch tit",
    "bitchass",
    "bitched",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchez",
    "bitchin",
    "bitching",
    "bitchtits",
    "bitchy",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "bloodclaat",
    "bloody",
    "bloody hell",
    "blow",
    "blow job",
    "blow me",
    "blow mud",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boang",
    "bod",
    "bodily",
    "bogan",
    "bohunk",
    "boink",
    "boiolas",
    "bollick",
    "bollock",
    "bollocks",
    "bollok",
    "bollox",
    "bomd",
    "bondage",
    "bone",
    "boned",
    "boner",
    "boners",
    "bong",
    "boob",
    "boobies",
    "boobs",
    "booby",
    "booger",
    "bookie",
    "boong",
    "boonga",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "bootee",
    "bootie",
    "booty",
    "booty call",
    "booze",
    "boozer",
    "boozy",
    "bosom",
    "bosomy",
    "bowel",
    "bowels",
    "bra",
    "brassiere",
    "breast",
    "breastjob",
    "breastlover",
    "breastman",
    "breasts",
    "breeder",
    "brotherfucker",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "buggered",
    "buggery",
    "bukkake",
    "bull shit",
    "bullcrap",
    "bulldike",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bullshits",
    "bullshitted",
    "bullturds",
    "bum",
    "bum boy",
    "bumblefuck",
    "bumclat",
    "bumfuck",
    "bummer",
    "bung",
    "bung hole",
    "bunga",
    "bunghole",
    "bunny fucker",
    "bust a load",
    "busty",
    "butchdike",
    "butchdyke",
    "butt",
    "butt fuck",
    "butt plug",
    "buttbang",
    "butt-bang",
    "buttcheeks",
    "buttface",
    "buttfuck",
    "butt-fuck",
    "buttfucka",
    "buttfucker",
    "butt-fucker",
    "butthead",
    "butthole",
    "buttman",
    "buttmuch",
    "buttmunch",
    "buttmuncher",
    "butt-pirate",
    "buttplug",
    "c.0.c.k",
    "c.o.c.k.",
    "c.u.n.t",
    "c0ck",
    "c-0-c-k",
    "c0cksucker",
    "caca",
    "cahone",
    "camel toe",
    "cameltoe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "cervix",
    "chesticle",
    "chi-chi man",
    "chick with a dick",
    "child-fucker",
    "chin",
    "chinc",
    "chincs",
    "chink",
    "chinky",
    "choad",
    "choade",
    "choc ice",
    "chocolate rosebuds",
    "chode",
    "chodes",
    "chota bags",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "climax",
    "clit",
    "clit licker",
    "clitface",
    "clitfuck",
    "clitoris",
    "clitorus",
    "clits",
    "clitty",
    "clitty litter",
    "clogwog",
    "clover clamps",
    "clunge",
    "clusterfuck",
    "cnut",
    "cocain",
    "cocaine",
    "cock",
    "c-o-c-k",
    "cock pocket",
    "cock snot",
    "cock sucker",
    "cockass",
    "cockbite",
    "cockblock",
    "cockburger",
    "cockeye",
    "cockface",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockjockey",
    "cockknocker",
    "cockknoker",
    "cocklicker",
    "cocklover",
    "cocklump",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cocks",
    "cockshit",
    "cocksmith",
    "cocksmoke",
    "cocksmoker",
    "cocksniffer",
    "cocksucer",
    "cocksuck",
    "cocksuck ",
    "cocksucked",
    "cocksucker",
    "cock-sucker",
    "cocksuckers",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cockwaffle",
    "coffin dodger",
    "coital",
    "cok",
    "cokmuncher",
    "coksucka",
    "commie",
    "condom",
    "coochie",
    "coochy",
    "coon",
    "coonnass",
    "coons",
    "cooter",
    "cop some wood",
    "coprolagnia",
    "coprophilia",
    "corksucker",
    "cornhole",
    "corp whore",
    "cox",
    "crabs",
    "crack",
    "cracker",
    "crackwhore",
    "crack-whore",
    "crap",
    "crappy",
    "creampie",
    "cretin",
    "crikey",
    "cripple",
    "crotte",
    "cum",
    "cum chugger",
    "cum dumpster",
    "cum freak",
    "cum guzzler",
    "cumbubble",
    "cumdump",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cummin",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cumstain",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunn",
    "cunnie",
    "cunnilingus",
    "cunntt",
    "cunny",
    "cunt",
    "c-u-n-t",
    "cunt hair",
    "cuntass",
    "cuntbag",
    "cuntface",
    "cuntfuck",
    "cuntfucker",
    "cunthole",
    "cunthunter",
    "cuntlick",
    "cuntlick ",
    "cuntlicker",
    "cuntlicker ",
    "cuntlicking",
    "cuntrag",
    "cunts",
    "cuntsicle",
    "cuntslut",
    "cunt-struck",
    "cuntsucker",
    "cut rope",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "cybersex",
    "d0ng",
    "d0uch3",
    "d0uche",
    "d1ck",
    "d1ld0",
    "d1ldo",
    "dago",
    "dagos",
    "dammit",
    "damn",
    "damned",
    "damnit",
    "darkie",
    "darn",
    "date rape",
    "daterape",
    "dawgie-style",
    "deep throat",
    "deepthroat",
    "deggo",
    "dendrophilia",
    "dick",
    "dick head",
    "dick hole",
    "dick shy",
    "dickbag",
    "dickbeaters",
    "dickbrain",
    "dickdipper",
    "dickface",
    "dickflipper",
    "dickfuck",
    "dickfucker",
    "dickhead",
    "dickheads",
    "dickhole",
    "dickish",
    "dick-ish",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickripper",
    "dicks",
    "dicksipper",
    "dickslap",
    "dick-sneeze",
    "dicksucker",
    "dicksucking",
    "dicktickler",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwhipper",
    "dickwod",
    "dickzipper",
    "diddle",
    "dike",
    "dildo",
    "dildos",
    "diligaf",
    "dillweed",
    "dimwit",
    "dingle",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dipship",
    "dipshit",
    "dirsa",
    "dirty",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggiestyle",
    "doggie-style",
    "doggin",
    "dogging",
    "doggy style",
    "doggystyle",
    "doggy-style",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "dong",
    "donkey punch",
    "donkeypunch",
    "donkeyribber",
    "doochbag",
    "doofus",
    "dookie",
    "doosh",
    "dopey",
    "double dong",
    "double penetration",
    "doublelift",
    "douch3",
    "douche",
    "douchebag",
    "douchebags",
    "douche-fag",
    "douchewaffle",
    "douchey",
    "dp action",
    "drunk",
    "dry hump",
    "duche",
    "dumass",
    "dumb ass",
    "dumbass",
    "dumbasses",
    "dumbcunt",
    "dumbfuck",
    "dumbshit",
    "dummy",
    "dumshit",
    "dvda",
    "dyke",
    "dykes",
    "eat a dick",
    "eat hair pie",
    "eat my ass",
    "eatpussy",
    "ecchi",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "enlargement",
    "erect",
    "erection",
    "erotic",
    "erotism",
    "escort",
    "essohbee",
    "eunuch",
    "extacy",
    "extasy",
    "f u c k",
    "f u c k e r",
    "f.u.c.k",
    "f_u_c_k",
    "f4nny",
    "facefucker",
    "facial",
    "fack",
    "fag",
    "fagbag",
    "fagfucker",
    "fagg",
    "fagged",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggotcock",
    "faggots",
    "faggs",
    "fagot",
    "fagots",
    "fags",
    "fagtard",
    "faig",
    "faigt",
    "fanny",
    "fannybandit",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fart",
    "fartknocker",
    "fastfuck",
    "fat",
    "fatass",
    "fatfuck",
    "fatfucker",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feck",
    "fecker",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "feltcher",
    "female squirting",
    "femdom",
    "fenian",
    "figging",
    "fingerbang",
    "fingerfuck",
    "fingerfuck ",
    "fingerfucked",
    "fingerfucker",
    "fingerfucker ",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fingering",
    "fist fuck",
    "fisted",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfucker ",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "fisting",
    "fisty",
    "flamer",
    "flange",
    "flaps",
    "fleshflute",
    "flog the log",
    "floozy",
    "foad",
    "foah",
    "fondle",
    "foobar",
    "fook",
    "fooker",
    "foot fetish",
    "footfuck",
    "footfucker",
    "footjob",
    "footlicker",
    "foreskin",
    "freakfuck",
    "freakyfucker",
    "freefuck",
    "freex",
    "frigg",
    "frigga",
    "frotting",
    "fubar",
    "fuc",
    "fuck",
    "f-u-c-k",
    "fuck buttons",
    "fuck hole",
    "fuck off",
    "fuck puppet",
    "fuck trophy",
    "fuck yo mama",
    "fuck you",
    "fucka",
    "fuckass",
    "fuck-ass",
    "fuckbag",
    "fuck-bitch",
    "fuckboy",
    "fuckbrain",
    "fuckbutt",
    "fuckbutter",
    "fucked",
    "fuckedup",
    "fucker",
    "fuckers",
    "fuckersucker",
    "fuckface",
    "fuckfreak",
    "fuckhead",
    "fuckheads",
    "fuckher",
    "fuckhole",
    "fuckin",
    "fucking",
    "fuckingbitch",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fuckme ",
    "fuckmeat",
    "fuckmehard",
    "fuckmonkey",
    "fucknugget",
    "fucknut",
    "fucknutt",
    "fuckoff",
    "fucks",
    "fuckstick",
    "fucktard",
    "fuck-tard",
    "fucktards",
    "fucktart",
    "fucktoy",
    "fucktwat",
    "fuckup",
    "fuckwad",
    "fuckwhit",
    "fuckwhore",
    "fuckwit",
    "fuckwitt",
    "fuckyou",
    "fudge packer",
    "fudgepacker",
    "fudge-packer",
    "fuk",
    "fuker",
    "fukker",
    "fukkers",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "fuq",
    "futanari",
    "fux",
    "fux0r",
    "fvck",
    "fxck",
    "gae",
    "gai",
    "gang bang",
    "gangbang",
    "gang-bang",
    "gangbanged",
    "gangbangs",
    "ganja",
    "gash",
    "gassy ass",
    "gay sex",
    "gayass",
    "gaybob",
    "gaydo",
    "gayfuck",
    "gayfuckist",
    "gaylord",
    "gays",
    "gaysex",
    "gaytard",
    "gaywad",
    "gender bender",
    "genitals",
    "gey",
    "gfy",
    "ghay",
    "ghey",
    "giant cock",
    "gigolo",
    "ginger",
    "gippo",
    "girl on",
    "girl on top",
    "girls gone wild",
    "git",
    "glans",
    "goatcx",
    "goatse",
    "god damn",
    "godamn",
    "godamnit",
    "goddam",
    "god-dam",
    "goddammit",
    "goddamn",
    "goddamned",
    "god-damned",
    "goddamnit",
    "goddamnmuthafucker",
    "godsdamn",
    "gokkun",
    "golden shower",
    "goldenshower",
    "golliwog",
    "gonad",
    "gonads",
    "gonorrehea",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "gooks",
    "goregasm",
    "gotohell",
    "gringo",
    "grope",
    "group sex",
    "gspot",
    "g-spot",
    "gtfo",
    "guido",
    "guro",
    "h0m0",
    "h0mo",
    "ham flap",
    "hand job",
    "handjob",
    "hard core",
    "hard on",
    "hardcore",
    "hardcoresex",
    "he11",
    "headfuck",
    "hebe",
    "heeb",
    "hell",
    "hemp",
    "hentai",
    "heroin",
    "herp",
    "herpes",
    "herpy",
    "heshe",
    "he-she",
    "hitler",
    "hiv",
    "ho",
    "hoar",
    "hoare",
    "hobag",
    "hoe",
    "hoer",
    "holy shit",
    "hom0",
    "homey",
    "homo",
    "homodumbshit",
    "homoerotic",
    "homoey",
    "honkey",
    "honky",
    "hooch",
    "hookah",
    "hooker",
    "hoor",
    "hootch",
    "hooter",
    "hooters",
    "hore",
    "horniest",
    "horny",
    "hot carl",
    "hot chick",
    "hotpussy",
    "hotsex",
    "how to kill",
    "how to murdep",
    "how to murder",
    "huge fat",
    "hump",
    "humped",
    "humping",
    "hun",
    "hussy",
    "hymen",
    "iap",
    "iberian slap",
    "inbred",
    "incest",
    "injun",
    "intercourse",
    "j3rk0ff",
    "jack off",
    "jackass",
    "jackasses",
    "jackhole",
    "jackoff",
    "jack-off",
    "jaggi",
    "jagoff",
    "jail bait",
    "jailbait",
    "jap",
    "japs",
    "jelly donut",
    "jerk",
    "jerk off",
    "jerk0ff",
    "jerkass",
    "jerked",
    "jerkoff",
    "jerk-off",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "jizzed",
    "jock",
    "juggs",
    "jungle bunny",
    "junglebunny",
    "junkie",
    "junky",
    "kafir",
    "kawk",
    "kike",
    "kikes",
    "kill",
    "kinbaku",
    "kinkster",
    "kinky",
    "kkk",
    "klan",
    "knob",
    "knob end",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kooches",
    "kootch",
    "kraut",
    "kum",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunja",
    "kunt",
    "kwif",
    "kyke",
    "l3i+ch",
    "l3itch",
    "labia",
    "lameass",
    "lardass",
    "leather restraint",
    "leather straight jacket",
    "lech",
    "lemon party",
    "leper",
    "lesbian",
    "lesbians",
    "lesbo",
    "lesbos",
    "lez",
    "lezbian",
    "lezbians",
    "lezbo",
    "lezbos",
    "lezza",
    "lezzie",
    "lezzies",
    "lezzy",
    "lmao",
    "lmfao",
    "loin",
    "loins",
    "lolita",
    "looney",
    "lovemaking",
    "lube",
    "lust",
    "lusting",
    "lusty",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "mafugly",
    "make me come",
    "male squirting",
    "mams",
    "masochist",
    "massa",
    "masterb8",
    "masterbat",
    "masterbat3",
    "masterbate",
    "master-bate",
    "masterbating",
    "masterbation",
    "masterbations",
    "masturbate",
    "masturbating",
    "masturbation",
    "maxi",
    "mcfagget",
    "menage a trois",
    "menses",
    "menstruate",
    "menstruation",
    "meth",
    "m-fucking",
    "mick",
    "middle finger",
    "midget",
    "milf",
    "minge",
    "minger",
    "missionary position",
    "mof0",
    "mofo",
    "mo-fo",
    "molest",
    "mong",
    "moo moo foo foo",
    "moolie",
    "moron",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucka",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "mound of venus",
    "mr hands",
    "mtherfucker",
    "mthrfucker",
    "mthrfucking",
    "muff",
    "muff diver",
    "muff puff",
    "muffdiver",
    "muffdiving",
    "munging",
    "munter",
    "murder",
    "mutha",
    "muthafecker",
    "muthafuckaz",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "mutherfucking",
    "muthrfucking",
    "n1gga",
    "n1gger",
    "nad",
    "nads",
    "naked",
    "nambla",
    "napalm",
    "nappy",
    "nawashi",
    "nazi",
    "nazism",
    "need the dick",
    "negro",
    "neonazi",
    "nig nog",
    "nigaboo",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "niggle",
    "niglet",
    "nig-nog",
    "nimphomania",
    "nimrod",
    "ninny",
    "nipple",
    "nipples",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nonce",
    "nooky",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nut butter",
    "nut sack",
    "nutsack",
    "nutter",
    "nympho",
    "nymphomania",
    "octopussy",
    "old bag",
    "omg",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "opiate",
    "opium",
    "oral",
    "orally",
    "organ",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasmic",
    "orgasms",
    "orgies",
    "orgy",
    "ovary",
    "ovum",
    "ovums",
    "p.u.s.s.y.",
    "p0rn",
    "paddy",
    "paedophile",
    "paki",
    "panooch",
    "pansy",
    "pantie",
    "panties",
    "panty",
    "pastie",
    "pasty",
    "pawn",
    "pcp",
    "pecker",
    "peckerhead",
    "pedo",
    "pedobear",
    "pedophile",
    "pedophilia",
    "pedophiliac",
    "pee",
    "peepee",
    "pegging",
    "penetrate",
    "penetration",
    "penial",
    "penile",
    "penis",
    "penisbanger",
    "penisfucker",
    "penispuffer",
    "perversion",
    "peyote",
    "phalli",
    "phallic",
    "phone sex",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "piece of shit",
    "pigfucker",
    "pikey",
    "pillowbiter",
    "pimp",
    "pimpis",
    "pinko",
    "piss",
    "piss off",
    "piss pig",
    "pissed",
    "pissed off",
    "pisser",
    "pissers",
    "pisses",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "piss-off",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pms",
    "polack",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poop",
    "poop chute",
    "poopchute",
    "poopuncher",
    "porch monkey",
    "porchmonkey",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "pot",
    "potty",
    "prick",
    "pricks",
    "prickteaser",
    "prig",
    "prince albert piercing",
    "prod",
    "pron",
    "prostitute",
    "prude",
    "psycho",
    "pthc",
    "pube",
    "pubes",
    "pubic",
    "pubis",
    "punani",
    "punanny",
    "punany",
    "punkass",
    "punky",
    "punta",
    "puss",
    "pusse",
    "pussi",
    "pussies",
    "pussy",
    "pussy fart",
    "pussy palace",
    "pussylicking",
    "pussypounder",
    "pussys",
    "pust",
    "puto",
    "queaf",
    "queef",
    "queer",
    "queerbait",
    "queerhole",
    "queero",
    "queers",
    "quicky",
    "quim",
    "racy",
    "raghead",
    "raging boner",
    "rape",
    "raped",
    "raper",
    "rapey",
    "raping",
    "rapist",
    "raunch",
    "rectal",
    "rectum",
    "rectus",
    "reefer",
    "reetard",
    "reich",
    "renob",
    "retard",
    "retarded",
    "reverse cowgirl",
    "revue",
    "rimjaw",
    "rimjob",
    "rimming",
    "ritard",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rtard",
    "r-tard",
    "rubbish",
    "rum",
    "rump",
    "rumprammer",
    "ruski",
    "rusty trombone",
    "s hit",
    "s&m",
    "s.h.i.t.",
    "s.o.b.",
    "s_h_i_t",
    "s0b",
    "sadism",
    "sadist",
    "sambo",
    "sand nigger",
    "sandbar",
    "sandler",
    "sandnigger",
    "sanger",
    "santorum",
    "sausage queen",
    "scag",
    "scantily",
    "scat",
    "schizo",
    "schlong",
    "scissoring",
    "screw",
    "screwed",
    "screwing",
    "scroat",
    "scrog",
    "scrot",
    "scrote",
    "scrotum",
    "scrud",
    "scum",
    "seaman",
    "seamen",
    "seduce",
    "seks",
    "semen",
    "sex",
    "sexo",
    "sexual",
    "sexy",
    "sh!+",
    "sh!t",
    "sh1t",
    "s-h-1-t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shamedame",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shi+",
    "shibari",
    "shirt lifter",
    "shit",
    "s-h-i-t",
    "shit ass",
    "shit fucker",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrains",
    "shitbreath",
    "shitcanned",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteater",
    "shited",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfuck",
    "shitfull",
    "shithead",
    "shitheads",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shits",
    "shitspitter",
    "shitstain",
    "shitt",
    "shitted",
    "shitter",
    "shitters",
    "shittier",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shiz",
    "shiznit",
    "shota",
    "shrimping",
    "sissy",
    "skag",
    "skank",
    "skeet",
    "skullfuck",
    "slag",
    "slanteye",
    "slave",
    "sleaze",
    "sleazy",
    "slope",
    "slut",
    "slut bucket",
    "slutbag",
    "slutdumper",
    "slutkiss",
    "sluts",
    "smartass",
    "smartasses",
    "smeg",
    "smegma",
    "smut",
    "smutty",
    "snatch",
    "sniper",
    "snowballing",
    "snuff",
    "s-o-b",
    "sod off",
    "sodom",
    "sodomize",
    "sodomy",
    "son of a bitch",
    "son of a motherless goat",
    "son of a whore",
    "son-of-a-bitch",
    "souse",
    "soused",
    "spac",
    "spade",
    "sperm",
    "spic",
    "spick",
    "spik",
    "spiks",
    "splooge",
    "splooge moose",
    "spooge",
    "spook",
    "spread legs",
    "spunk",
    "steamy",
    "stfu",
    "stiffy",
    "stoned",
    "strap on",
    "strapon",
    "strappado",
    "strip",
    "strip club",
    "stroke",
    "stupid",
    "style doggy",
    "suck",
    "suckass",
    "sucked",
    "sucking",
    "sucks",
    "suicide girls",
    "sultry women",
    "sumofabiatch",
    "swastika",
    "swinger",
    "t1t",
    "t1tt1e5",
    "t1tties",
    "taff",
    "taig",
    "tainted love",
    "taking the piss",
    "tampon",
    "tard",
    "tart",
    "taste my",
    "tawdry",
    "tea bagging",
    "teabagging",
    "teat",
    "teets",
    "teez",
    "terd",
    "teste",
    "testee",
    "testes",
    "testical",
    "testicle",
    "testis",
    "threesome",
    "throating",
    "thrust",
    "thug",
    "thundercunt",
    "tied up",
    "tight white",
    "tinkle",
    "tit",
    "tit wank",
    "titfuck",
    "titi",
    "tities",
    "tits",
    "titt",
    "tittie5",
    "tittiefucker",
    "titties",
    "titty",
    "tittyfuck",
    "tittyfucker",
    "tittywank",
    "titwank",
    "toke",
    "tongue in a",
    "toots",
    "topless",
    "tosser",
    "towelhead",
    "tramp",
    "tranny",
    "transsexual",
    "trashy",
    "tribadism",
    "trumped",
    "tub girl",
    "tubgirl",
    "turd",
    "tush",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twats",
    "twatty",
    "twatwaffle",
    "twink",
    "twinkie",
    "two fingers",
    "two fingers with tongue",
    "two girls one cup",
    "twunt",
    "twunter",
    "ugly",
    "unclefucker",
    "undies",
    "undressing",
    "unwed",
    "upskirt",
    "urethra play",
    "urinal",
    "urine",
    "urophilia",
    "uterus",
    "uzi",
    "v14gra",
    "v1gra",
    "vag",
    "vagina",
    "vajayjay",
    "va-j-j",
    "valium",
    "venus mound",
    "veqtable",
    "viagra",
    "vibrator",
    "violet wand",
    "virgin",
    "vixen",
    "vjayjay",
    "vodka",
    "vomit",
    "vorarephilia",
    "voyeur",
    "vulgar",
    "vulva",
    "w00se",
    "wad",
    "wang",
    "wank",
    "wanker",
    "wankjob",
    "wanky",
    "wazoo",
    "wedgie",
    "weed",
    "weenie",
    "weewee",
    "weiner",
    "weirdo",
    "wench",
    "wet dream",
    "wetback",
    "wh0re",
    "wh0reface",
    "white power",
    "whitey",
    "whiz",
    "whoar",
    "whoralicious",
    "whore",
    "whorealicious",
    "whorebag",
    "whored",
    "whoreface",
    "whorehopper",
    "whorehouse",
    "whores",
    "whoring",
    "wigger",
    "willies",
    "willy",
    "window licker",
    "wiseass",
    "wiseasses",
    "wog",
    "womb",
    "woody",
    "wop",
    "wrapping men",
    "wrinkled starfish",
    "wtf",
    "xrated",
    "x-rated",
    "xx",
    "xxx",
    "yaoi",
    "yeasty",
    "yellow showers",
    "yid",
    "yiffy",
    "yobbo",
    "zoophile",
    "zoophilia",
    "zubb",
    "---------",
    "A level",
    "a-word",
    "abstract",
    "abstraction",
    "accident",
    "accountant",
    "acopia",
    "act of darkness",
    "adult actress",
    "adult material",
    "adult movie",
    "adult star",
    "age out",
    "ager",
    "alternative lifestyle",
    "anatomically correct",
    "anatomy",
    "angel baby",
    "angel maker",
    "angel mom",
    "another place",
    "answer the call of nature",
    "anticipatory retaliation",
    "appointment in Samarra",
    "approach",
    "argument",
    "arouse",
    "artistic temperament",
    "Aryan",
    "as heck",
    "asleep",
    "at liberty",
    "at peace",
    "at rest",
    "auger in",
    "Aunt Flo",
    "aurally challenged",
    "authority issues",
    "autolyzed yeast extract",
    "b-word",
    "BA",
    "back alley",
    "back passage",
    "back-butt",
    "backhouse",
    "backside",
    "bally",
    "banana split",
    "bank holiday",
    "bar sinister",
    "barking spider",
    "barn door",
    "basket",
    "bass-ackwards",
    "bat for both sides",
    "bat for the other team",
    "bathroom",
    "bathroom tissue",
    "batspit",
    "be with",
    "beach",
    "beast with two backs",
    "beat the poop out of",
    "become one with one's inner self",
    "beep",
    "bejeebus",
    "bejesus",
    "Bent Spear",
    "between jobs",
    "between wind and water",
    "biblically",
    "big C",
    "big D",
    "Big Game",
    "big sleep",
    "big-boned",
    "binch",
    "bio-break",
    "birds and bees",
    "bite the dust",
    "black ace",
    "black dog",
    "black ivory",
    "blamed",
    "blanked",
    "blankety",
    "blarmed",
    "blazes",
    "bleep",
    "bleeping",
    "blessed",
    "blessed assurance",
    "blessed event",
    "blinking",
    "block and tackle",
    "bloody heck",
    "blooming",
    "blooming heck",
    "blow off",
    "blue falcon",
    "bluggy",
    "BM",
    "BO",
    "bodily function",
    "bog",
    "bog off",
    "boneless lean beef trimmings",
    "bonus mother",
    "boom-boom",
    "born sleeping",
    "Botany Bay fever",
    "bouncy-bouncy",
    "bovine scatology",
    "bow chicka wow wow",
    "box",
    "boylove",
    "boylover",
    "brave",
    "break wind",
    "Broken Arrow",
    "BS",
    "BSer",
    "BTM",
    "bucket of sunshine",
    "built like a brick outhouse",
    "built like a brick shipyard",
    "bull",
    "bull butter",
    "bull gravy",
    "bullbleep",
    "bullcrud",
    "bulldung",
    "bullocks",
    "bullplop",
    "bullpoop",
    "bullpucky",
    "bullscheisse",
    "bullsnot",
    "bullspit",
    "bullswool",
    "bump purses",
    "buns",
    "business girl",
    "butcher boy",
    "butthole",
    "buy the farm",
    "by gannies",
    "by gummy",
    "c-word",
    "caboose",
    "call of nature",
    "callboy",
    "calling card",
    "can",
    "candy man",
    "capitation",
    "career-limiting move",
    "cargo-200",
    "casting couch",
    "catch the bus",
    "caught short",
    "celebrating Palm Sunday",
    "cement shoes",
    "central adiposity",
    "cerebrally challenged",
    "cerebrovascular accident",
    "challenged",
    "chamber-work",
    "chambers",
    "change of life",
    "check out",
    "check-out time",
    "cheese and rice",
    "cheese pizza",
    "cheeses",
    "chemical imbalance",
    "chemically imbalanced",
    "chemically inconvenienced",
    "chesterfield rugby",
    "childlove",
    "childlover",
    "chimney",
    "chit",
    "chuck you Farley",
    "chunky",
    "climax",
    "cloakroom",
    "close one's eyes and think of England",
    "close one's eyes for the last time",
    "closet of decency",
    "closet of ease",
    "clucking",
    "cluster",
    "clusterball",
    "clusterbumble",
    "clusterfrack",
    "cock sock",
    "collateral damage",
    "colorful",
    "comfort break",
    "comfort girl",
    "comfort station",
    "comfort woman",
    "commode",
    "commons",
    "commotion",
    "community cat",
    "confirmed bachelor",
    "confound it",
    "consanguinamory",
    "consort",
    "constitutional",
    "coprophagous grin",
    "cornfield meet",
    "correction center",
    "correction centre",
    "correctional center",
    "correctional centre",
    "correctional facility",
    "correctional institution",
    "corrections center",
    "corrections centre",
    "course",
    "courses",
    "cover one's feet",
    "CP",
    "crapshow",
    "crapstorm",
    "creative accounting",
    "creative differences",
    "crimson tide",
    "cripes",
    "cross over",
    "crotch",
    "crud",
    "cubes",
    "culinarily challenged",
    "cull",
    "culture",
    "cunning linguist",
    "cunning linguistics",
    "Cupid's disease",
    "Cupid's Disease",
    "curtain",
    "curvy",
    "cut the cheese",
    "cut the umbilical cord",
    "cycler",
    "D",
    "d-word",
    "dad burn",
    "dad-blamed",
    "dadburn",
    "dadgum",
    "dadgummit",
    "daggum",
    "dagnab",
    "dagnammit",
    "dance",
    "dancer",
    "dang",
    "dangly bits",
    "dangnabbit",
    "darn",
    "darn right",
    "darned",
    "darnedest",
    "darnfool",
    "dash",
    "dash it",
    "dashed",
    "daughter of joy",
    "debt of nature",
    "decades young",
    "decruit",
    "defense",
    "deflation",
    "dehire",
    "demnition",
    "depart",
    "departed",
    "departure",
    "deuced",
    "developmental disability",
    "devil",
    "devil's doorbell",
    "dickens",
    "differently able",
    "dignity",
    "ding dong",
    "dip one's pen in someone's inkwell",
    "diphead",
    "dirt sandwich",
    "disadvantaged",
    "disappeared",
    "discuss Uganda",
    "Distinguished Competition",
    "do away with",
    "do it",
    "do one's business",
    "do one's darnedest",
    "do one's duty",
    "do one's ease",
    "do one's easement",
    "do the deed",
    "do the nasty",
    "do you need to use the bathroom",
    "does a bear poop in the woods",
    "dog dirt",
    "doggone",
    "doggonit",
    "dogpile",
    "domestic engineer",
    "doo-doo",
    "doodie head",
    "doodoohead",
    "dormition",
    "double-u",
    "down below",
    "down the cludgie",
    "down the tubes",
    "down there",
    "down under",
    "downbelows",
    "downsize",
    "downstairs",
    "dress",
    "drinkologist",
    "drive the porcelain bus",
    "drop a bomb",
    "drop a chalupa",
    "drop a deuce",
    "drop a log",
    "drop anchor",
    "drop off the hooks",
    "drop the f-bomb",
    "drop the kids off at the pool",
    "ducking",
    "dumb cluck",
    "dumbcluck",
    "dump",
    "dunny",
    "durn",
    "durnfool",
    "early bath",
    "ease",
    "ease nature",
    "ease oneself",
    "easement",
    "eat for two",
    "economical with the truth",
    "eff",
    "eff all",
    "eff off",
    "eff up",
    "effer",
    "effing",
    "employmentally challenged",
    "Empty Quiver",
    "energetic disassembly",
    "energetic event",
    "English vice",
    "enhanced",
    "enhanced interrogation",
    "enhanced interrogation technique",
    "escort",
    "estate",
    "esthetically challenged",
    "eternal sleep",
    "ethically challenged",
    "ethnically challenged",
    "ethnicity",
    "Eve-teasing",
    "exchange flesh",
    "exit",
    "exotic cheroot",
    "exotic dancer",
    "expiration",
    "expletive deleted",
    "explicit",
    "expose oneself",
    "extract the urine",
    "eye-opener",
    "F",
    "F off",
    "f-bomb",
    "f-slur",
    "f-word",
    "Citations:F-word",
    "FA",
    "fabulous",
    "facetiae",
    "facilities",
    "facts of life",
    "facts on the ground",
    "Faded Giant",
    "faith-based",
    "fall",
    "fall asleep",
    "fall asleep in the Lord",
    "fall off a truck",
    "fall off the back of a lorry",
    "fall off the back of a truck",
    "family jewels",
    "famine resistant",
    "fancy house",
    "fanny",
    "farm upstate",
    "fboy",
    "feck",
    "feel no pain",
    "feeling no pain",
    "feet first",
    "fiddlesticks",
    "FIGMO",
    "fill one's pants",
    "find a friendly bush",
    "firetruck",
    "five-finger discount",
    "flabbergasted",
    "flip",
    "flipping",
    "flower",
    "fluff",
    "flying fig",
    "flying toilet",
    "follicly challenged",
    "follow through",
    "for cripes' sake",
    "for fudge's sake",
    "for goodness' sake",
    "for goodness' sakes",
    "for heaven's sake",
    "for mercy's sake",
    "for Pete's sake",
    "for pity's sake",
    "for the love of Betsy",
    "for the love of Mike",
    "fork",
    "fork off",
    "forkhead",
    "foxtrot oscar",
    "frack",
    "fracking",
    "fragrant meat",
    "frail sister",
    "frak",
    "freak",
    "freaking",
    "freaking gosh",
    "free helicopter ride",
    "French",
    "French disease",
    "French letter",
    "French safe",
    "French vice",
    "frick",
    "fricker",
    "fricking",
    "friend",
    "friend of Bill W.",
    "friend of Dorothy",
    "friendship with benefits",
    "frig",
    "frig off",
    "frigg",
    "frigger",
    "frigging",
    "front bottom",
    "front bum",
    "front butt",
    "front line",
    "fruit and flowers",
    "fsck",
    "fuddle-duddle",
    "fudge",
    "fudge it",
    "fug",
    "fugg",
    "fugged",
    "fugghead",
    "fuggheaded",
    "fuggheadedness",
    "fugging",
    "full of it",
    "full service",
    "full-throated",
    "fun house",
    "fun size",
    "functioning",
    "funny boy",
    "fustercluck",
    "futhermucker",
    "g-word",
    "G-word",
    "gall dang",
    "gamer word",
    "Gawd",
    "gay lady",
    "gazelle in the garden",
    "gazelle on the lawn",
    "GD",
    "GDI",
    "geez",
    "generative",
    "gentleman cow",
    "gentlemen's",
    "gentlemen's club",
    "gentlemen's room",
    "gents",
    "geography",
    "German vice",
    "get",
    "get into trouble",
    "get it",
    "get off at Haymarket",
    "get off at Redfern",
    "get one's a into g",
    "get sick",
    "get some",
    "get stuffed",
    "getting any",
    "getting enough",
    "getting some",
    "gingerbread office",
    "girllove",
    "girllover",
    "give a darn",
    "give a rats",
    "give one's all",
    "give someone the time",
    "Glasgow kiss",
    "go all the way",
    "go at it",
    "go down on",
    "go down the drain",
    "go down the pan",
    "go down the tubes",
    "go f oneself",
    "go gentle into that good night",
    "go home",
    "go oof",
    "go over to the majority",
    "go the way of all flesh",
    "go to bed with",
    "go to blazes",
    "go to pot",
    "go to Putney on a pig",
    "go to sleep",
    "go to the bathroom",
    "go to the restroom",
    "go to the toilet",
    "go to the washroom",
    "goldamned",
    "goldarn",
    "goldarned",
    "golden years",
    "goldurn",
    "goldurnit",
    "goll",
    "golly",
    "gom",
    "gone with the wind",
    "good gracious",
    "good-time girl",
    "goodness",
    "goodness gracious",
    "gorry",
    "gosh all hemlock",
    "gosh darn",
    "goshawful",
    "goshawfully",
    "goshdang",
    "goshdanged",
    "goshdangit",
    "goshdarn",
    "goshdarned",
    "goshdarnit",
    "goshdurn",
    "government man",
    "gratuity",
    "gravitationally challenged",
    "groin",
    "guarded",
    "gutter rabbit",
    "h-word",
    "habit-forming",
    "half-mast",
    "halmoni",
    "handyman's special",
    "hang it",
    "hanged",
    "happy as a pig in mud",
    "happy ending",
    "harvest",
    "haul one's ashes",
    "have it away",
    "have marital relations",
    "have one's way",
    "have one's way with",
    "have seen better days",
    "have the painters in",
    "have work done",
    "HE-double-hockey-sticks",
    "HE-double-L",
    "HE-double-toothpicks",
    "heck",
    "heck no",
    "heck of a",
    "heckfire",
    "heckhound",
    "heliolatry",
    "hempen collar",
    "hempen cravat",
    "hide the sausage",
    "high tide",
    "hills and valleys",
    "hinder",
    "holy carp",
    "holy cow",
    "holy doodle",
    "holy fudge",
    "holy macaroni",
    "holy mackerel",
    "holy moley",
    "honey bucket",
    "honeypot",
    "honour killing",
    "hoo-ha",
    "hoo-hoo",
    "horizontal",
    "horizontal dancing",
    "horizontal hula",
    "horizontal jogging",
    "horizontal mambo",
    "horizontal polka",
    "horizontal refreshments",
    "horizontal tango",
    "horizontalize",
    "horizontally challenged",
    "Horlicks",
    "horse hockey",
    "horse pucky",
    "horsefeathers",
    "horsepoop",
    "hostess bar",
    "hot dang",
    "house in Virginia",
    "house of accommodation",
    "House of Commons",
    "house of ease",
    "house of easement",
    "house of ill fame",
    "house of ill repute",
    "House of Lords",
    "house of office",
    "how do you do",
    "how's your father",
    "humanly challenged",
    "husky",
    "hydrolyzed vegetable protein",
    "hymenally challenged",
    "i-word",
    "I'll be blowed",
    "I'll be dipped",
    "ill repute",
    "I'm thirsty",
    "in a box",
    "in a family way",
    "in all one's glory",
    "in deep doo-doo",
    "in the altogether",
    "in the bedroom",
    "in the biblical sense",
    "in the club",
    "in the family way",
    "in the racket",
    "in the raw",
    "in trouble",
    "indisposed",
    "innie",
    "innings",
    "inspect the plumbing",
    "intellectually challenged",
    "interesting",
    "interesting condition",
    "internment camp",
    "intimate area",
    "invasive carp",
    "irregularity",
    "ish",
    "issue",
    "itshay",
    "j- words",
    "jack",
    "jerkin the gherkin",
    "Jesum Crow",
    "jigger",
    "jiggered",
    "jiggery-pokery",
    "Jiminy Cricket",
    "jimjam",
    "job creator",
    "join the choir invisible",
    "Judas Priest",
    "judenrein",
    "k-words",
    "keep company",
    "keep the wolf from the door",
    "khazi",
    "kick off",
    "kick someone's butt",
    "kick the bucket",
    "kinetic",
    "knock boots",
    "l -words",
    "L-rd",
    "ladies",
    "ladies'",
    "ladies and gentlemen",
    "ladies' cloakroom",
    "ladies' room",
    "lady abbess",
    "lady friend",
    "lady of leisure",
    "lady of light virtue",
    "lady of the evening",
    "lady of the night",
    "lady parts",
    "ladybits",
    "ladyparts",
    "land shrimp",
    "lap",
    "last roundup",
    "late",
    "late unpleasantness",
    "lavabo",
    "lavatory",
    "lawful interception",
    "lay down",
    "leak",
    "lean finely textured beef",
    "learning difficulty",
    "let go",
    "let someone go",
    "let's go Brandon",
    "let's go, Brandon",
    "liberate",
    "lie back and think of England",
    "lie with",
    "light in the loafers",
    "light on one's feet",
    "like that",
    "lingam",
    "liquid gold",
    "liquidation",
    "little boy's room",
    "little boys room",
    "little boys' room",
    "little girl's room",
    "little girls room",
    "little girls' room",
    "little green man",
    "little head",
    "little man",
    "little person",
    "little woman",
    "lived-in",
    "living impaired",
    "LMHO",
    "load",
    "loins",
    "lone rangering",
    "long pig",
    "long pork",
    "long-eared guinea pig",
    "longhouse",
    "lorks",
    "lose one's cookies",
    "lose one's life",
    "loss of life",
    "lost in action",
    "love",
    "love child",
    "love handle",
    "loved one",
    "low-information",
    "low-T",
    "lubrication payment",
    "m-word",
    "machine",
    "make",
    "make love",
    "make water",
    "male enhancement",
    "male member",
    "mamma jamma",
    "manhood",
    "manliness",
    "manure",
    "MAP",
    "marital aid",
    "marital duties",
    "marital embrace",
    "marriage bed",
    "mass debate",
    "maypole",
    "meet one's maker",
    "member",
    "memory care",
    "men's room",
    "mentally challenged",
    "merry",
    "mess",
    "metabolically challenged",
    "middle leg",
    "minced oath",
    "minor-attracted person",
    "mischief",
    "mommy juice",
    "Montezuma's revenge",
    "monthly",
    "monthly bill",
    "monthly friend",
    "monthly visitor",
    "moonlight requisition",
    "mother",
    "motherchucker",
    "motherfather",
    "motherferyer",
    "motherfouler",
    "motherfreaking",
    "motherfricker",
    "motherfunker",
    "motherhumper",
    "motherlover",
    "motherloving",
    "mother's little helper",
    "mothertrucker",
    "mothertrucking",
    "motion",
    "move one's bowels",
    "muddy",
    "multicultural",
    "my gosh",
    "n- words",
    "n-bomb",
    "n-word",
    "nasty",
    "NatSoc",
    "nature",
    "nature calls",
    "naughty bit",
    "necessary",
    "necessary house",
    "necessary place",
    "necessary room",
    "necessary stool",
    "necessary vault",
    "nerts",
    "Netflix and chill",
    "nether cheek",
    "nether region",
    "netty",
    "neutralize",
    "newfriend",
    "nibba",
    "nice guy",
    "nicker",
    "night soil",
    "night-soil",
    "nightwalker",
    "nightwalking",
    "no better than one ought to be",
    "no excrement, Sherlock",
    "no longer with us",
    "no wuckas",
    "no-no spot",
    "not a pretty sight",
    "not Pygmalion likely",
    "not right in the head",
    "not the sharpest crayon in the box",
    "not the sharpest knife in the drawer",
    "not the sharpest tool in the box",
    "not the sharpest tool in the shed",
    "NQR",
    "nucking futs",
    "number one",
    "number two",
    "nymph of darkness",
    "nymph of the pavement",
    "o-words",
    "of a certain age",
    "office",
    "officer-involved",
    "officer-involved shooting",
    "oh my",
    "oh my days",
    "oh my goodness gracious",
    "oh my gosh",
    "oh my heck",
    "oh my lanta",
    "Old Gentleman",
    "old time used to be",
    "older adult",
    "oldest occupation",
    "on",
    "on in years",
    "on one's period",
    "on the beat",
    "on the down-low",
    "on the game",
    "on the rag",
    "on the turf",
    "on the way out",
    "one",
    "ongoer",
    "open one's bowels",
    "other end",
    "other head",
    "other virginity",
    "out of the picture",
    "outie",
    "over-unity",
    "overnourished",
    "overrefreshed",
    "p-words",
    "P U",
    "p.o.'ed",
    "package",
    "pain in the backside",
    "parentally challenged",
    "part-time girlfriend",
    "parts",
    "party",
    "party favor",
    "party girl",
    "pass away",
    "pass gas",
    "pass on",
    "pass over",
    "pass the river",
    "pass water",
    "pass wind",
    "passage",
    "pattern up",
    "pay a visit",
    "pay the debt of nature",
    "payroll",
    "p'd off",
    "PDQ",
    "pearl",
    "peas and rice",
    "peculiar institution",
    "pee",
    "pee in someone's cornflakes",
    "pee like a racehorse",
    "pee off",
    "peed off",
    "period",
    "Persian love",
    "person",
    "personal",
    "pet stain",
    "petty",
    "petty-house",
    "physically challenged",
    "pick flowers",
    "piddle",
    "piddle away",
    "pike",
    "pinch a loaf",
    "pine box",
    "pink oboe",
    "place",
    "play silly beggars",
    "play with oneself",
    "playmate",
    "pleasures of the flesh",
    "plot",
    "PO'd",
    "polish one's rocket",
    "poo",
    "pooh",
    "poop",
    "poop sandwich",
    "post-kinetic",
    "posterior",
    "pot",
    "potty mouth",
    "powder one's nose",
    "powder room",
    "powder rooms",
    "PR-friendly",
    "prairie dog",
    "pre-owned",
    "pre-viewed",
    "preloved",
    "pretty horsebreaker",
    "previously disadvantaged",
    "primrose path",
    "private",
    "private parts",
    "problem child",
    "professional",
    "protected democracy",
    "protective reaction",
    "proverbial",
    "pucky",
    "pudenda muliebria",
    "puella publica",
    "pulling the plug",
    "pushing up daisies",
    "put down",
    "put on the block",
    "put to sleep",
    "q - word",
    "Quincy",
    "r - words",
    "r-slur",
    "r-slurred",
    "rabbit raisins",
    "race realism",
    "racially challenged",
    "rainbow bridge",
    "rapid unplanned disassembly",
    "rarted",
    "reality challenged",
    "recreational medicine",
    "red day",
    "red ink",
    "reduced circumstances",
    "reduction in force",
    "reeducation",
    "relieve",
    "relieve nature",
    "relieve oneself",
    "removal",
    "rest",
    "rest in peace",
    "resting",
    "resting place",
    "restorative",
    "restroom",
    "resurrection man",
    "resurrectionist",
    "retreat",
    "return to dust",
    "rhymes-with-rich",
    "ride the cotton bicycle",
    "ride the cotton horse",
    "ride the cotton pony",
    "rightsize",
    "rip someone a new one",
    "rise to the occasion",
    "rock",
    "rock and roll",
    "roll in the hay",
    "Roman hands and Russian fingers",
    "romancing the bone",
    "romp in the hay",
    "roof rabbit",
    "rootless cosmopolitan",
    "rough sleeper",
    "rubber-hose cryptanalysis",
    "RUD",
    "rumpty-tumpty",
    "s - words",
    "s-bomb",
    "sanitaries",
    "scared shirtless",
    "scared spitless",
    "scheisse",
    "science",
    "seat of ease",
    "security forces",
    "seduce",
    "see a man",
    "see a man about a dog",
    "see a man about a horse",
    "see the back of",
    "see to",
    "see you next Tuesday",
    "select out",
    "self-abuse",
    "self-abuser",
    "self-defilement",
    "self-delete",
    "self-deletion",
    "self-gratification",
    "self-love",
    "self-pleasing",
    "self-pollute",
    "self-pollution",
    "sell",
    "send to the glue factory",
    "service",
    "service oneself",
    "sex",
    "sexual marketplace",
    "shake hands with the unemployed",
    "share a bed",
    "shedload",
    "sheesh",
    "shield",
    "shizzle",
    "shmexy",
    "shoot",
    "short on looks",
    "show oneself",
    "shower",
    "shucks",
    "shuffle off this mortal coil",
    "shut one's eyes and think of England",
    "shut the fridge",
    "shut the front door",
    "siegehouse",
    "silence",
    "silent majority",
    "simple",
    "sing soprano",
    "singing soprano",
    "sister humper",
    "six feet under",
    "skid mark",
    "skidmark",
    "skunkbag",
    "sleep around",
    "sleep of the just",
    "sleep together",
    "sleep with",
    "slimwear",
    "slip away",
    "slip into something more comfortable",
    "slipper",
    "small room",
    "smallest room",
    "smallest room in the house",
    "smartsize",
    "smartsizing",
    "SNAFU",
    "snip",
    "snow on the mountaintop",
    "snow on the rooftop",
    "snowball's chance in heck",
    "snuff it",
    "so-and-so",
    "SOAB",
    "social evil",
    "soft ordnance",
    "soil",
    "soil oneself",
    "soiled dove",
    "solo sex",
    "something for the weekend",
    "son of a",
    "son of a gun",
    "son of a snake",
    "son-of-a-gun stew",
    "Spanish athlete",
    "special",
    "special lassi",
    "special military operation",
    "spend a penny",
    "spill one's seed",
    "spithole",
    "starlight tour",
    "start",
    "states' rights",
    "stay up",
    "stem the rose",
    "still with us",
    "stinking",
    "stool",
    "stool of easement",
    "street pharmacist",
    "stuff",
    "stuff you",
    "suck cheese",
    "sugar honey ice tea",
    "sumbuck",
    "superb owl",
    "supratentorial",
    "surplus to requirements",
    "Suzie Wong",
    "swash someone's buckle",
    "sweet science",
    "sweet spot",
    "sweetshop",
    "swing that way",
    "syphon the python",
    "t- words",
    "take a dump",
    "take a leak",
    "take care of",
    "take care of business",
    "take French leave",
    "take the Michael",
    "take the pee",
    "talk out of one's ear",
    "tarnal",
    "tarnation",
    "teach the controversy",
    "teahouse",
    "tear someone a new one",
    "tearoom",
    "tell someone where to shove it",
    "temporal",
    "terminate",
    "terminate with extreme prejudice",
    "terminological inexactitude",
    "testilie",
    "testilying",
    "that way",
    "that way inclined",
    "the bad place",
    "the change",
    "the dickens",
    "the dickens you say",
    "the heck",
    "the last favour",
    "the measles",
    "the other place",
    "the rabbit died",
    "thingy",
    "think of England",
    "think with one's little head",
    "throne",
    "throne room",
    "thump",
    "time of the month",
    "tinkle",
    "tip someone's velvet",
    "tired and emotional",
    "to heck in a handbasket",
    "toilet",
    "toilet humour",
    "toilet room",
    "toilet training",
    "Tom",
    "TOM",
    "touch oneself",
    "tract of land",
    "trainable",
    "transition",
    "trouser cough",
    "trouser department",
    "Trudeau salute",
    "trump",
    "truncheon",
    "try",
    "tuppence",
    "tweep",
    "twig and berries",
    "u-words",
    "uckfay",
    "Ugandan",
    "Ugandan affairs",
    "Ugandan discussions",
    "unalive",
    "uncle",
    "undercarriage",
    "underendowed",
    "undocumented worker",
    "unfortunate",
    "unhire",
    "unibody",
    "union",
    "unmentionables",
    "unwell",
    "up poo creek",
    "up the proverbial",
    "upstairs",
    "urban",
    "use it",
    "use the bathroom",
    "use the restroom",
    "use the toilet",
    "use the washroom",
    "usual offices",
    "v-words",
    "V",
    "V card",
    "va-jay-jay",
    "vajay",
    "variety meat",
    "vault",
    "vehicularly challenged",
    "vehicularly housed",
    "vertically challenged",
    "violate",
    "violation",
    "vitally challenged",
    "vitamin P",
    "w-words",
    "walk",
    "walk the dog",
    "wardrobe",
    "wardrobe malfunction",
    "wash one's hands",
    "washroom",
    "waterworks",
    "way of all flesh",
    "well-covered",
    "well-endowed",
    "well-padded",
    "well-upholstered",
    "wet",
    "wet job",
    "wet the bed",
    "wet work",
    "what the cuss",
    "what the eff",
    "what the fudge",
    "what the hay",
    "what the heck",
    "what the hey",
    "what the what",
    "whatever it takes",
    "when heck freezes over",
    "where it counts",
    "where the heck",
    "where the sun don't shine",
    "whiskey tango foxtrot",
    "white light",
    "wick",
    "wide stance",
    "witch's water",
    "with child",
    "with God",
    "with the Lord",
    "without",
    "woman of ill fame",
    "woman of ill repute",
    "woman of the night",
    "woman of the street",
    "woman of the town",
    "womanhood",
    "women's room",
    "women's troubles",
    "woods colt",
    "work nights",
    "working girl",
    "world's oldest profession",
    "wuckin'",
    "wucking",
    "y- words",
    "yarbles",
    "ye gods",
    "years young",
    "ying-yang",
    "Yoshke",
    "youthful indiscretion",
    "yuck",
    "z-words",
    "zark",
    "zarking",
]
euphe = [

    "A level",
    "a-word",
    "abstract",
    "abstraction",
    "accident",
    "accountant",
    "acopia",
    "act of darkness",
    "adult actress",
    "adult material",
    "adult movie",
    "adult star",
    "age out",
    "ager",
    "alternative lifestyle",
    "anatomically correct",
    "anatomy",
    "angel baby",
    "angel maker",
    "angel mom",
    "another place",
    "answer the call of nature",
    "anticipatory retaliation",
    "appointment in Samarra",
    "approach",
    "argument",
    "arouse",
    "artistic temperament",
    "Aryan",
    "as heck",
    "asleep",
    "at liberty",
    "at peace",
    "at rest",
    "auger in",
    "Aunt Flo",
    "aurally challenged",
    "authority issues",
    "autolyzed yeast extract",
    "b-word",
    "BA",
    "back alley",
    "back passage",
    "back-butt",
    "backhouse",
    "backside",
    "bally",
    "banana split",
    "bank holiday",
    "bar sinister",
    "barking spider",
    "barn door",
    "basket",
    "bass-ackwards",
    "bat for both sides",
    "bat for the other team",
    "bathroom",
    "bathroom tissue",
    "batspit",
    "be with",
    "beach",
    "beast with two backs",
    "beat the poop out of",
    "become one with one's inner self",
    "beep",
    "bejeebus",
    "bejesus",
    "Bent Spear",
    "between jobs",
    "between wind and water",
    "biblically",
    "big C",
    "big D",
    "Big Game",
    "big sleep",
    "big-boned",
    "binch",
    "bio-break",
    "birds and bees",
    "bite the dust",
    "black ace",
    "black dog",
    "black ivory",
    "blamed",
    "blanked",
    "blankety",
    "blarmed",
    "blazes",
    "bleep",
    "bleeping",
    "blessed",
    "blessed assurance",
    "blessed event",
    "blinking",
    "block and tackle",
    "bloody heck",
    "blooming",
    "blooming heck",
    "blow off",
    "blue falcon",
    "bluggy",
    "BM",
    "BO",
    "bodily function",
    "bog",
    "bog off",
    "boneless lean beef trimmings",
    "bonus mother",
    "boom-boom",
    "born sleeping",
    "Botany Bay fever",
    "bouncy-bouncy",
    "bovine scatology",
    "bow chicka wow wow",
    "box",
    "boylove",
    "boylover",
    "brave",
    "break wind",
    "Broken Arrow",
    "BS",
    "BSer",
    "BTM",
    "bucket of sunshine",
    "built like a brick outhouse",
    "built like a brick shipyard",
    "bull",
    "bull butter",
    "bull gravy",
    "bullbleep",
    "bullcrud",
    "bulldung",
    "bullocks",
    "bullplop",
    "bullpoop",
    "bullpucky",
    "bullscheisse",
    "bullsnot",
    "bullspit",
    "bullswool",
    "bump purses",
    "buns",
    "business girl",
    "butcher boy",
    "butthole",
    "buy the farm",
    "by gannies",
    "by gummy",
    "c-word",
    "caboose",
    "call of nature",
    "callboy",
    "calling card",
    "can",
    "candy man",
    "capitation",
    "career-limiting move",
    "cargo-200",
    "casting couch",
    "catch the bus",
    "caught short",
    "celebrating Palm Sunday",
    "cement shoes",
    "central adiposity",
    "cerebrally challenged",
    "cerebrovascular accident",
    "challenged",
    "chamber-work",
    "chambers",
    "change of life",
    "check out",
    "check-out time",
    "cheese and rice",
    "cheese pizza",
    "cheeses",
    "chemical imbalance",
    "chemically imbalanced",
    "chemically inconvenienced",
    "chesterfield rugby",
    "childlove",
    "childlover",
    "chimney",
    "chit",
    "chuck you Farley",
    "chunky",
    "climax",
    "cloakroom",
    "close one's eyes and think of England",
    "close one's eyes for the last time",
    "closet of decency",
    "closet of ease",
    "clucking",
    "cluster",
    "clusterball",
    "clusterbumble",
    "clusterfrack",
    "cock sock",
    "collateral damage",
    "colorful",
    "comfort break",
    "comfort girl",
    "comfort station",
    "comfort woman",
    "commode",
    "commons",
    "commotion",
    "community cat",
    "confirmed bachelor",
    "confound it",
    "consanguinamory",
    "consort",
    "constitutional",
    "coprophagous grin",
    "cornfield meet",
    "correction center",
    "correction centre",
    "correctional center",
    "correctional centre",
    "correctional facility",
    "correctional institution",
    "corrections center",
    "corrections centre",
    "course",
    "courses",
    "cover one's feet",
    "CP",
    "crapshow",
    "crapstorm",
    "creative accounting",
    "creative differences",
    "crimson tide",
    "cripes",
    "cross over",
    "crotch",
    "crud",
    "cubes",
    "culinarily challenged",
    "cull",
    "culture",
    "cunning linguist",
    "cunning linguistics",
    "Cupid's disease",
    "Cupid's Disease",
    "curtain",
    "curvy",
    "cut the cheese",
    "cut the umbilical cord",
    "cycler",
    "D",
    "d-word",
    "dad burn",
    "dad-blamed",
    "dadburn",
    "dadgum",
    "dadgummit",
    "daggum",
    "dagnab",
    "dagnammit",
    "dance",
    "dancer",
    "dang",
    "dangly bits",
    "dangnabbit",
    "darn",
    "darn right",
    "darned",
    "darnedest",
    "darnfool",
    "dash",
    "dash it",
    "dashed",
    "daughter of joy",
    "debt of nature",
    "decades young",
    "decruit",
    "defense",
    "deflation",
    "dehire",
    "demnition",
    "depart",
    "departed",
    "departure",
    "deuced",
    "developmental disability",
    "devil",
    "devil's doorbell",
    "dickens",
    "differently able",
    "dignity",
    "ding dong",
    "dip one's pen in someone's inkwell",
    "diphead",
    "dirt sandwich",
    "disadvantaged",
    "disappeared",
    "discuss Uganda",
    "Distinguished Competition",
    "do away with",
    "do it",
    "do one's business",
    "do one's darnedest",
    "do one's duty",
    "do one's ease",
    "do one's easement",
    "do the deed",
    "do the nasty",
    "do you need to use the bathroom",
    "does a bear poop in the woods",
    "dog dirt",
    "doggone",
    "doggonit",
    "dogpile",
    "domestic engineer",
    "doo-doo",
    "doodie head",
    "doodoohead",
    "dormition",
    "double-u",
    "down below",
    "down the cludgie",
    "down the tubes",
    "down there",
    "down under",
    "downbelows",
    "downsize",
    "downstairs",
    "dress",
    "drinkologist",
    "drive the porcelain bus",
    "drop a bomb",
    "drop a chalupa",
    "drop a deuce",
    "drop a log",
    "drop anchor",
    "drop off the hooks",
    "drop the f-bomb",
    "drop the kids off at the pool",
    "ducking",
    "dumb cluck",
    "dumbcluck",
    "dump",
    "dunny",
    "durn",
    "durnfool",
    "early bath",
    "ease",
    "ease nature",
    "ease oneself",
    "easement",
    "eat for two",
    "economical with the truth",
    "eff",
    "eff all",
    "eff off",
    "eff up",
    "effer",
    "effing",
    "employmentally challenged",
    "Empty Quiver",
    "energetic disassembly",
    "energetic event",
    "English vice",
    "enhanced",
    "enhanced interrogation",
    "enhanced interrogation technique",
    "escort",
    "estate",
    "esthetically challenged",
    "eternal sleep",
    "ethically challenged",
    "ethnically challenged",
    "ethnicity",
    "Eve-teasing",
    "exchange flesh",
    "exit",
    "exotic cheroot",
    "exotic dancer",
    "expiration",
    "expletive deleted",
    "explicit",
    "expose oneself",
    "extract the urine",
    "eye-opener",
    "F",
    "F off",
    "f-bomb",
    "f-slur",
    "f-word",
    "Citations:F-word",
    "FA",
    "fabulous",
    "facetiae",
    "facilities",
    "facts of life",
    "facts on the ground",
    "Faded Giant",
    "faith-based",
    "fall",
    "fall asleep",
    "fall asleep in the Lord",
    "fall off a truck",
    "fall off the back of a lorry",
    "fall off the back of a truck",
    "family jewels",
    "famine resistant",
    "fancy house",
    "fanny",
    "farm upstate",
    "fboy",
    "feck",
    "feel no pain",
    "feeling no pain",
    "feet first",
    "fiddlesticks",
    "FIGMO",
    "fill one's pants",
    "find a friendly bush",
    "firetruck",
    "five-finger discount",
    "flabbergasted",
    "flip",
    "flipping",
    "flower",
    "fluff",
    "flying fig",
    "flying toilet",
    "follicly challenged",
    "follow through",
    "for cripes' sake",
    "for fudge's sake",
    "for goodness' sake",
    "for goodness' sakes",
    "for heaven's sake",
    "for mercy's sake",
    "for Pete's sake",
    "for pity's sake",
    "for the love of Betsy",
    "for the love of Mike",
    "fork",
    "fork off",
    "forkhead",
    "foxtrot oscar",
    "frack",
    "fracking",
    "fragrant meat",
    "frail sister",
    "frak",
    "freak",
    "freaking",
    "freaking gosh",
    "free helicopter ride",
    "French",
    "French disease",
    "French letter",
    "French safe",
    "French vice",
    "frick",
    "fricker",
    "fricking",
    "friend",
    "friend of Bill W.",
    "friend of Dorothy",
    "friendship with benefits",
    "frig",
    "frig off",
    "frigg",
    "frigger",
    "frigging",
    "front bottom",
    "front bum",
    "front butt",
    "front line",
    "fruit and flowers",
    "fsck",
    "fuddle-duddle",
    "fudge",
    "fudge it",
    "fug",
    "fugg",
    "fugged",
    "fugghead",
    "fuggheaded",
    "fuggheadedness",
    "fugging",
    "full of it",
    "full service",
    "full-throated",
    "fun house",
    "fun size",
    "functioning",
    "funny boy",
    "fustercluck",
    "futhermucker",
    "g-word",
    "G-word",
    "gall dang",
    "gamer word",
    "Gawd",
    "gay lady",
    "gazelle in the garden",
    "gazelle on the lawn",
    "GD",
    "GDI",
    "geez",
    "generative",
    "gentleman cow",
    "gentlemen's",
    "gentlemen's club",
    "gentlemen's room",
    "gents",
    "geography",
    "German vice",
    "get",
    "get into trouble",
    "get it",
    "get off at Haymarket",
    "get off at Redfern",
    "get one's a into g",
    "get sick",
    "get some",
    "get stuffed",
    "getting any",
    "getting enough",
    "getting some",
    "gingerbread office",
    "girllove",
    "girllover",
    "give a darn",
    "give a rats",
    "give one's all",
    "give someone the time",
    "Glasgow kiss",
    "go all the way",
    "go at it",
    "go down on",
    "go down the drain",
    "go down the pan",
    "go down the tubes",
    "go f oneself",
    "go gentle into that good night",
    "go home",
    "go oof",
    "go over to the majority",
    "go the way of all flesh",
    "go to bed with",
    "go to blazes",
    "go to pot",
    "go to Putney on a pig",
    "go to sleep",
    "go to the bathroom",
    "go to the restroom",
    "go to the toilet",
    "go to the washroom",
    "goldamned",
    "goldarn",
    "goldarned",
    "golden years",
    "goldurn",
    "goldurnit",
    "goll",
    "golly",
    "gom",
    "gone with the wind",
    "good gracious",
    "good-time girl",
    "goodness",
    "goodness gracious",
    "gorry",
    "gosh all hemlock",
    "gosh darn",
    "goshawful",
    "goshawfully",
    "goshdang",
    "goshdanged",
    "goshdangit",
    "goshdarn",
    "goshdarned",
    "goshdarnit",
    "goshdurn",
    "government man",
    "gratuity",
    "gravitationally challenged",
    "groin",
    "guarded",
    "gutter rabbit",
    "h-word",
    "habit-forming",
    "half-mast",
    "halmoni",
    "handyman's special",
    "hang it",
    "hanged",
    "happy as a pig in mud",
    "happy ending",
    "harvest",
    "haul one's ashes",
    "have it away",
    "have marital relations",
    "have one's way",
    "have one's way with",
    "have seen better days",
    "have the painters in",
    "have work done",
    "HE-double-hockey-sticks",
    "HE-double-L",
    "HE-double-toothpicks",
    "heck",
    "heck no",
    "heck of a",
    "heckfire",
    "heckhound",
    "heliolatry",
    "hempen collar",
    "hempen cravat",
    "hide the sausage",
    "high tide",
    "hills and valleys",
    "hinder",
    "holy carp",
    "holy cow",
    "holy doodle",
    "holy fudge",
    "holy macaroni",
    "holy mackerel",
    "holy moley",
    "honey bucket",
    "honeypot",
    "honour killing",
    "hoo-ha",
    "hoo-hoo",
    "horizontal",
    "horizontal dancing",
    "horizontal hula",
    "horizontal jogging",
    "horizontal mambo",
    "horizontal polka",
    "horizontal refreshments",
    "horizontal tango",
    "horizontalize",
    "horizontally challenged",
    "Horlicks",
    "horse hockey",
    "horse pucky",
    "horsefeathers",
    "horsepoop",
    "hostess bar",
    "hot dang",
    "house in Virginia",
    "house of accommodation",
    "House of Commons",
    "house of ease",
    "house of easement",
    "house of ill fame",
    "house of ill repute",
    "House of Lords",
    "house of office",
    "how do you do",
    "how's your father",
    "humanly challenged",
    "husky",
    "hydrolyzed vegetable protein",
    "hymenally challenged",
    "i-word",
    "I'll be blowed",
    "I'll be dipped",
    "ill repute",
    "I'm thirsty",
    "in a box",
    "in a family way",
    "in all one's glory",
    "in deep doo-doo",
    "in the altogether",
    "in the bedroom",
    "in the biblical sense",
    "in the club",
    "in the family way",
    "in the racket",
    "in the raw",
    "in trouble"
,
    "indisposed",
    "innie",
    "innings",
    "inspect the plumbing",
    "intellectually challenged",
    "interesting",
    "interesting condition",
    "internment camp",
    "intimate area",
    "invasive carp",
    "irregularity",
    "ish",
    "issue",
    "itshay",
    "j- words",
    "jack",
    "jerkin the gherkin",
    "Jesum Crow",
    "jigger",
    "jiggered",
    "jiggery-pokery",
    "Jiminy Cricket",
    "jimjam",
    "job creator",
    "join the choir invisible",
    "Judas Priest",
    "judenrein",
    "k-words",
    "keep company",
    "keep the wolf from the door",
    "khazi",
    "kick off",
    "kick someone's butt",
    "kick the bucket",
    "kinetic",
    "knock boots",
    "l -words",
    "L-rd",
    "ladies",
    "ladies'",
    "ladies and gentlemen",
    "ladies' cloakroom",
    "ladies' room",
    "lady abbess",
    "lady friend",
    "lady of leisure",
    "lady of light virtue",
    "lady of the evening",
    "lady of the night",
    "lady parts",
    "ladybits",
    "ladyparts",
    "land shrimp",
    "lap",
    "last roundup",
    "late",
    "late unpleasantness",
    "lavabo",
    "lavatory",
    "lawful interception",
    "lay down",
    "leak",
    "lean finely textured beef",
    "learning difficulty",
    "let go",
    "let someone go",
    "let's go Brandon",
    "let's go, Brandon",
    "liberate",
    "lie back and think of England",
    "lie with",
    "light in the loafers",
    "light on one's feet",
    "like that",
    "lingam",
    "liquid gold",
    "liquidation",
    "little boy's room",
    "little boys room",
    "little boys' room",
    "little girl's room",
    "little girls room",
    "little girls' room",
    "little green man",
    "little head",
    "little man",
    "little person",
    "little woman",
    "lived-in",
    "living impaired",
    "LMHO",
    "load",
    "loins",
    "lone rangering",
    "long pig",
    "long pork",
    "long-eared guinea pig",
    "longhouse",
    "lorks",
    "lose one's cookies",
    "lose one's life",
    "loss of life",
    "lost in action",
    "love",
    "love child",
    "love handle",
    "loved one",
    "low-information",
    "low-T",
    "lubrication payment",
    "m-word",
    "machine",
    "make",
    "make love",
    "make water",
    "male enhancement",
    "male member",
    "mamma jamma",
    "manhood",
    "manliness",
    "manure",
    "MAP",
    "marital aid",
    "marital duties",
    "marital embrace",
    "marriage bed",
    "mass debate",
    "maypole",
    "meet one's maker",
    "member",
    "memory care",
    "men's room",
    "mentally challenged",
    "merry",
    "mess",
    "metabolically challenged",
    "middle leg",
    "minced oath",
    "minor-attracted person",
    "mischief",
    "mommy juice",
    "Montezuma's revenge",
    "monthly",
    "monthly bill",
    "monthly friend",
    "monthly visitor",
    "moonlight requisition",
    "mother",
    "motherchucker",
    "motherfather",
    "motherferyer",
    "motherfouler",
    "motherfreaking",
    "motherfricker",
    "motherfunker",
    "motherhumper",
    "motherlover",
    "motherloving",
    "mother's little helper",
    "mothertrucker",
    "mothertrucking",
    "motion",
    "move one's bowels",
    "muddy",
    "multicultural",
    "my gosh",
    "n- words",
    "n-bomb",
    "n-word",
    "nasty",
    "NatSoc",
    "nature",
    "nature calls",
    "naughty bit",
    "necessary",
    "necessary house",
    "necessary place",
    "necessary room",
    "necessary stool",
    "necessary vault",
    "nerts",
    "Netflix and chill",
    "nether cheek",
    "nether region",
    "netty",
    "neutralize",
    "newfriend",
    "nibba",
    "nice guy",
    "nicker",
    "night soil",
    "night-soil",
    "nightwalker",
    "nightwalking",
    "no better than one ought to be",
    "no excrement, Sherlock",
    "no longer with us",
    "no wuckas",
    "no-no spot",
    "not a pretty sight",
    "not Pygmalion likely",
    "not right in the head",
    "not the sharpest crayon in the box",
    "not the sharpest knife in the drawer",
    "not the sharpest tool in the box",
    "not the sharpest tool in the shed",
    "NQR",
    "nucking futs",
    "number one",
    "number two",
    "nymph of darkness",
    "nymph of the pavement",
    "o-words",
    "of a certain age",
    "office",
    "officer-involved",
    "officer-involved shooting",
    "oh my",
    "oh my days",
    "oh my goodness gracious",
    "oh my gosh",
    "oh my heck",
    "oh my lanta",
    "Old Gentleman",
    "old time used to be",
    "older adult",
    "oldest occupation",
    "on",
    "on in years",
    "on one's period",
    "on the beat",
    "on the down-low",
    "on the game",
    "on the rag",
    "on the turf",
    "on the way out",
    "one",
    "ongoer",
    "open one's bowels",
    "other end",
    "other head",
    "other virginity",
    "out of the picture",
    "outie",
    "over-unity",
    "overnourished",
    "overrefreshed",
    "p-words",
    "P U",
    "p.o.'ed",
    "package",
    "pain in the backside",
    "parentally challenged",
    "part-time girlfriend",
    "parts",
    "party",
    "party favor",
    "party girl",
    "pass away",
    "pass gas",
    "pass on",
    "pass over",
    "pass the river",
    "pass water",
    "pass wind",
    "passage",
    "pattern up",
    "pay a visit",
    "pay the debt of nature",
    "payroll",
    "p'd off",
    "PDQ",
    "pearl",
    "peas and rice",
    "peculiar institution",
    "pee",
    "pee in someone's cornflakes",
    "pee like a racehorse",
    "pee off",
    "peed off",
    "period",
    "Persian love",
    "person",
    "personal",
    "pet stain",
    "petty",
    "petty-house",
    "physically challenged",
    "pick flowers",
    "piddle",
    "piddle away",
    "pike",
    "pinch a loaf",
    "pine box",
    "pink oboe",
    "place",
    "play silly beggars",
    "play with oneself",
    "playmate",
    "pleasures of the flesh",
    "plot",
    "PO'd",
    "polish one's rocket",
    "poo",
    "pooh",
    "poop",
    "poop sandwich",
    "post-kinetic",
    "posterior",
    "pot",
    "potty mouth",
    "powder one's nose",
    "powder room",
    "powder rooms",
    "PR-friendly",
    "prairie dog",
    "pre-owned",
    "pre-viewed",
    "preloved",
    "pretty horsebreaker",
    "previously disadvantaged",
    "primrose path",
    "private",
    "private parts",
    "problem child",
    "professional",
    "protected democracy",
    "protective reaction",
    "proverbial",
    "pucky",
    "pudenda muliebria",
    "puella publica",
    "pulling the plug",
    "pushing up daisies",
    "put down",
    "put on the block",
    "put to sleep",
    "q - word",
    "Quincy",
    "r - words",
    "r-slur",
    "r-slurred",
    "rabbit raisins",
    "race realism",
    "racially challenged",
    "rainbow bridge",
    "rapid unplanned disassembly",
    "rarted",
    "reality challenged",
    "recreational medicine",
    "red day",
    "red ink",
    "reduced circumstances",
    "reduction in force",
    "reeducation",
    "relieve",
    "relieve nature",
    "relieve oneself",
    "removal",
    "rest",
    "rest in peace",
    "resting",
    "resting place",
    "restorative",
    "restroom",
    "resurrection man",
    "resurrectionist",
    "retreat",
    "return to dust",
    "rhymes-with-rich",
    "ride the cotton bicycle",
    "ride the cotton horse",
    "ride the cotton pony",
    "rightsize",
    "rip someone a new one",
    "rise to the occasion",
    "rock",
    "rock and roll",
    "roll in the hay",
    "Roman hands and Russian fingers",
    "romancing the bone",
    "romp in the hay",
    "roof rabbit",
    "rootless cosmopolitan",
    "rough sleeper",
    "rubber-hose cryptanalysis",
    "RUD",
    "rumpty-tumpty",
    "s - words",
    "s-bomb",
    "sanitaries",
    "scared shirtless",
    "scared spitless",
    "scheisse",
    "science",
    "seat of ease",
    "security forces",
    "seduce",
    "see a man",
    "see a man about a dog",
    "see a man about a horse",
    "see the back of",
    "see to",
    "see you next Tuesday",
    "select out",
    "self-abuse",
    "self-abuser",
    "self-defilement",
    "self-delete",
    "self-deletion",
    "self-gratification",
    "self-love",
    "self-pleasing",
    "self-pollute",
    "self-pollution",
    "sell",
    "send to the glue factory",
    "service",
    "service oneself",
    "sex",
    "sexual marketplace",
    "shake hands with the unemployed",
    "share a bed",
    "shedload",
    "sheesh",
    "shield",
    "shizzle",
    "shmexy",
    "shoot",
    "short on looks",
    "show oneself",
    "shower",
    "shucks",
    "shuffle off this mortal coil",
    "shut one's eyes and think of England",
    "shut the fridge",
    "shut the front door",
    "siegehouse",
    "silence",
    "silent majority",
    "simple",
    "sing soprano",
    "singing soprano",
    "sister humper",
    "six feet under",
    "skid mark",
    "skidmark",
    "skunkbag",
    "sleep around",
    "sleep of the just",
    "sleep together",
    "sleep with",
    "slimwear",
    "slip away",
    "slip into something more comfortable",
    "slipper",
    "small room",
    "smallest room",
    "smallest room in the house",
    "smartsize",
    "smartsizing",
    "SNAFU",
    "snip",
    "snow on the mountaintop",
    "snow on the rooftop",
    "snowball's chance in heck",
    "snuff it",
    "so-and-so",
    "SOAB",
    "social evil",
    "soft ordnance",
    "soil",
    "soil oneself",
    "soiled dove",
    "solo sex",
    "something for the weekend",
    "son of a",
    "son of a gun",
    "son of a snake",
    "son-of-a-gun stew",
    "Spanish athlete",
    "special",
    "special lassi",
    "special military operation",
    "spend a penny",
    "spill one's seed",
    "spithole",
    "starlight tour",
    "start",
    "states' rights",
    "stay up",
    "stem the rose",
    "still with us",
    "stinking",
    "stool",
    "stool of easement",
    "street pharmacist",
    "stuff",
    "stuff you",
    "suck cheese",
    "sugar honey ice tea",
    "sumbuck",
    "superb owl",
    "supratentorial",
    "surplus to requirements",
    "Suzie Wong",
    "swash someone's buckle",
    "sweet science",
    "sweet spot",
    "sweetshop",
    "swing that way",
    "syphon the python",
    "t- words",
    "take a dump",
    "take a leak",
    "take care of",
    "take care of business",
    "take French leave",
    "take the Michael",
    "take the pee",
    "talk out of one's ear",
    "tarnal",
    "tarnation",
    "teach the controversy",
    "teahouse",
    "tear someone a new one",
    "tearoom",
    "tell someone where to shove it",
    "temporal",
    "terminate",
    "terminate with extreme prejudice",
    "terminological inexactitude",
    "testilie",
    "testilying",
    "that way",
    "that way inclined",
    "the bad place",
    "the change",
    "the dickens",
    "the dickens you say",
    "the heck",
    "the last favour",
    "the measles",
    "the other place",
    "the rabbit died",
    "thingy",
    "think of England",
    "think with one's little head",
    "throne",
    "throne room",
    "thump",
    "time of the month",
    "tinkle",
    "tip someone's velvet",
    "tired and emotional",
    "to heck in a handbasket",
    "toilet",
    "toilet humour",
    "toilet room",
    "toilet training",
    "Tom",
    "TOM",
    "touch oneself",
    "tract of land",
    "trainable",
    "transition",
    "trouser cough",
    "trouser department",
    "Trudeau salute",
    "trump",
    "truncheon",
    "try",
    "tuppence",
    "tweep",
    "twig and berries",
    "u-words",
    "uckfay",
    "Ugandan",
    "Ugandan affairs",
    "Ugandan discussions",
    "unalive",
    "uncle",
    "undercarriage",
    "underendowed",
    "undocumented worker",
    "unfortunate",
    "unhire",
    "unibody",
    "union",
    "unmentionables",
    "unwell",
    "up poo creek",
    "up the proverbial",
    "upstairs",
    "urban",
    "use it",
    "use the bathroom",
    "use the restroom",
    "use the toilet",
    "use the washroom",
    "usual offices",
    "v-words",
    "V",
    "V card",
    "va-jay-jay",
    "vajay",
    "variety meat",
    "vault",
    "vehicularly challenged",
    "vehicularly housed",
    "vertically challenged",
    "violate",
    "violation",
    "vitally challenged",
    "vitamin P",
    "w-words",
    "walk",
    "walk the dog",
    "wardrobe",
    "wardrobe malfunction",
    "wash one's hands",
    "washroom",
    "waterworks",
    "way of all flesh",
    "well-covered",
    "well-endowed",
    "well-padded",
    "well-upholstered",
    "wet",
    "wet job",
    "wet the bed",
    "wet work",
    "what the cuss",
    "what the eff",
    "what the fudge",
    "what the hay",
    "what the heck",
    "what the hey",
    "what the what",
    "whatever it takes",
    "when heck freezes over",
    "where it counts",
    "where the heck",
    "where the sun don't shine",
    "whiskey tango foxtrot",
    "white light",
    "wick",
    "wide stance",
    "witch's water",
    "with child",
    "with God",
    "with the Lord",
    "without",
    "woman of ill fame",
    "woman of ill repute",
    "woman of the night",
    "woman of the street",
    "woman of the town",
    "womanhood",
    "women's room",
    "women's troubles",
    "woods colt",
    "work nights",
    "working girl",
    "world's oldest profession",
    "wuckin'",
    "wucking",
    "y- words",
    "yarbles",
    "ye gods",
    "years young",
    "ying-yang",
    "Yoshke",
    "youthful indiscretion",
    "yuck",
    "z-words",
    "zark",
    "zarking",
]
leet = {
    "1": "i",
    "3": "e",
    "4": "a",
    "5": "s",
    "7": "t",
    "0": "o",
    "@": "a",
    "/\ ": "a",
    "/-\ ": "a",
    "*": "a",
    "ä": "a",
    "á": "a",
    "à": "a",
    "â": "a",
    "a^": "a",
    "ã": "a",
    "å": "a",
    "ą": "a",
    "ª": "a",
    "∀": "a",
    "∧": "a",
    "α": "a",
    "8": "b",
    "|3": "b",
    "13": "b",
    "ß": "b",
    "þ": "b",
    "v": "b",
    "ć": "c",
    "č": "c",
    "ç": "c",
    "©": "c",
    "σ": "c",
    "(": "c",
    "¢": "c",
    "<": "c",
    '[': "c",
    '©': "c",
    "[)": "d",
    "|>": "d",
    "|)": "d",
    "|]": "d",
    "3": "e",
    "€": "e",
    "є": "e",
    "[-": "e",
    "|=": "f",
    "ƒ": "f",
    "/=": "f",
    "6": "g",
    "(_+": "g",
    "#": "h",
    "/-/": "h",
    "[-]": "h",
    "]-[": "h",
    ")-(": "h",
    "(-)": "h",
    ":-:": "h",
    "|~|": "h",
    "|-|": "h",
    "]~[": "h",
    "}{": "h",
    "1": "i",
    '!': "i",
    "|": "i",
    "][": "i",
    "]": "i",
    ":": "i",
    "_|": "j",
    "_/": "j",
    "¿": "j",
    "(/": "j",
    "ʝ": "j",
    ";": "j",
    "X": "k",
    "|<": "k",
    "|{": "k",
    "ɮ": "k",
    "£": "l",
    "1_": "l",
    "ℓ": "l",
    "|_": "l",
    "[_": "l",
    "|V|": "m",
    "|\/|": "m",
    "/\/\ ": "m",
    "/V\ ": "m",
    "|V": "n",
    "|\|": "n",
    "/\/": "n",
    "[\]": "n",
    "/V": "n",
    "[]": "o",
    "0": "o",
    "()": "o",
    "°": "o",
    "|*": "p",
    "|o": "p",
    "|º": "p",
    "|°": "p",
    "/*": "p",
    "¶": "q",
    "(_,)": "q",
    "()_": "q",
    "0_": "q",
    "°|": "q",
    "<|": "q",
    "®": "r",
    "2": "r",
    "|?": "r",
    "/2": "r",
    "®": "r",
    "Я": "r",
    "|2": "r",
    "§": "s",
    "5": "s",
    "$": "s",
    "_/¯": "s",
    "7": "t",
    "†": "t",
    "¯|¯": "t",
    "(_)": "u",
    "|_|": "u",
    "L|": "u",
    "µ": "u",
    "\/": "v",
    "|/": "v",
    "\/\/": "w",
    "vv": "w",
    "\//": "w",
    "\^/": "w",
    "\V/": "w",
    "\|/": "w",
    "\_|_/": "w",
    "\_:_/": "w",
    "><": "x",
    "}{": "x",
    "×": "x",
    ")(": "x",
    " `/": "y",
    "φ": "y",
    "¥": "y",
    "\/": "y",
    "≥": "z",
    "7_": "z",
    ">_": "z"
}


def process_text(raw_text):
    # Convert leet speak to regular text
    for key, value in leet.items():
        text = text.replace(key, value)

    # Normalize text
    raw_text.lower()
    raw_text = re.sub(r"[^a-z0-9]+", " ", raw_text)

    # Tokenize Text
    tokens = nltk.word_tokenize(raw_text)

    # badwords, euphe, threshold = 0.9


def filter_and_replace(text):
    # define a regular expression to extract words from the text
    word_regex = r'\b\w+\b'

    # extract the words from the text
    words = re.findall(word_regex, text)

    # iterate over the words and check if they are similar to any of the banned words
    filtered_words = []
    for word in range(len(words)):
        for profane in badwords:
            flag = [jellyfish.jaro_similarity(word, profane)]
            if (flag > 0.9):
                filtered_words.append(word)
    filtered_text = " ".join(filtered_words)
    return filtered_text
    #     word_similarity_scores = [jellyfish.jaro_similarity(word, profane)]
    #     max_similarity_score = max(word_similarity_scores)
    #
    #     if max_similarity_score > threshold:
    #         # get the index of the euphemism with the highest similarity score
    #         max_similarity_index = word_similarity_scores.index(max_similarity_score)
    #         filtered_words.append(euphe[max_similarity_index])
    #     else:
    #         filtered_words.append(word)
    #         # filtered_words+=1
    #
    # # join the filtered words back into a string
    # filtered_text = " ".join(filtered_words)
    #
    # return filtered_text


text = "hahahaha fucking piece of shit"
filtered_text = filter_and_replace(text)
print("Original Text: ", text)
print("Filtered Text: ", filtered_text)